name: ddro
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.0.2
      - dill==0.3.8
      - docstring-parser==0.16
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gdown==5.2.0
      - gensim==3.8.1
      - huggingface-hub==0.25.2
      - idna==3.10
      - joblib==1.4.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nanopq==0.2.1
      - nltk==3.9.1
      - numpy==1.26.0
      - packaging==24.1
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - responses==0.18.0
      - rich==13.9.2
      - sacremoses==0.1.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - shtab==1.7.1
      - six==1.16.0
      - smart-open==7.0.5
      - soupsieve==2.6
      - threadpoolctl==3.5.0
      - tokenizers==0.20.1
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.66.5
      - transformers==4.45.2
      - trl==0.11.4
      - typing-extensions==4.12.2
      - tyro==0.8.12
      - tzdata==2024.2
      - urllib3==2.2.3
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.15.3
